/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atividadesextras;

import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *
 * @author Kauã Rodrigo
 */
public class JogoDaVelha extends javax.swing.JFrame {
    /**
     * Creates new form JogoDaVelha
     */
    boolean clicouBotao[] = new boolean[9];

    boolean vezJogador = false;

    String nomeJogadores[] = new String[2];

    public JogoDaVelha() {

        initComponents();

        Arrays.fill(clicouBotao, false);

        nomeJogadores[0] = JOptionPane.showInputDialog(null, "Digite o nome do jogador 1" );
        nomeJogadores[1] = JOptionPane.showInputDialog(null, "Digite o nome do jogador 2");

        nomeJogador.setText(nomeJogadores[0]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bn3 = new javax.swing.JButton();
        bn1 = new javax.swing.JButton();
        bn2 = new javax.swing.JButton();
        bn6 = new javax.swing.JButton();
        bn4 = new javax.swing.JButton();
        bn5 = new javax.swing.JButton();
        bn9 = new javax.swing.JButton();
        bn7 = new javax.swing.JButton();
        bn8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeJogador = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn3.setForeground(new java.awt.Color(0, 0, 0));
        bn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn3ActionPerformed(evt);
            }
        });

        bn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn1.setForeground(new java.awt.Color(0, 0, 0));
        bn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1ActionPerformed(evt);
            }
        });

        bn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn2.setForeground(new java.awt.Color(0, 0, 0));
        bn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn2ActionPerformed(evt);
            }
        });

        bn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn6.setForeground(new java.awt.Color(0, 0, 0));
        bn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn6ActionPerformed(evt);
            }
        });

        bn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn4.setForeground(new java.awt.Color(0, 0, 0));
        bn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn4ActionPerformed(evt);
            }
        });

        bn5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn5.setForeground(new java.awt.Color(0, 0, 0));
        bn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn5ActionPerformed(evt);
            }
        });

        bn9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn9.setForeground(new java.awt.Color(0, 0, 0));
        bn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn9ActionPerformed(evt);
            }
        });

        bn7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn7.setForeground(new java.awt.Color(0, 0, 0));
        bn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn7ActionPerformed(evt);
            }
        });

        bn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bn8.setForeground(new java.awt.Color(0, 0, 0));
        bn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Jogo da Velha");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Jogador Atual: ");

        nomeJogador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeJogador.setForeground(new java.awt.Color(255, 51, 51));
        nomeJogador.setText("Vazio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeJogador)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(bn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bn4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bn7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeJogador))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn3ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[2] == false) {
            mudar(bn3);
            clicouBotao[2] = true;
        }

    }//GEN-LAST:event_bn3ActionPerformed

    private void bn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[0] == false) {
            mudar(bn1);
            clicouBotao[0] = true;
        }

    }//GEN-LAST:event_bn1ActionPerformed

    private void bn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn2ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[1] == false) {
            mudar(bn2);
            clicouBotao[1] = true;
        }

    }//GEN-LAST:event_bn2ActionPerformed

    private void bn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn6ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[5] == false) {
            mudar(bn6);
            clicouBotao[5] = true;
        }

    }//GEN-LAST:event_bn6ActionPerformed

    private void bn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn4ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[3] == false) {
            mudar(bn4);
            clicouBotao[3] = true;
        }

    }//GEN-LAST:event_bn4ActionPerformed

    private void bn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn5ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[4] == false) {
            mudar(bn5);
            clicouBotao[4] = true;
        }

    }//GEN-LAST:event_bn5ActionPerformed

    private void bn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn9ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[8] == false) {
            mudar(bn9);
            clicouBotao[8] = true;
        } 

    }//GEN-LAST:event_bn9ActionPerformed

    private void bn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn7ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[6] == false) {
            mudar(bn7);
            clicouBotao[6] = true;
        }

    }//GEN-LAST:event_bn7ActionPerformed

    private void bn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn8ActionPerformed
        // TODO add your handling code here:

        if (clicouBotao[7] == false) {
            mudar(bn8);
            clicouBotao[7] = true;
        }

    }//GEN-LAST:event_bn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDaVelha().setVisible(true);
            }
        });
    }

    public void mudar(javax.swing.JButton button) { //Alternar a vez do jogador

        if (vezJogador == true) {
            button.setText("O");
            vezJogador = false;
            nomeJogador.setText(nomeJogadores[0]);
        } else {
            button.setText("X");
            vezJogador = true;
            nomeJogador.setText(nomeJogadores[1]);
        }

        ganhou();

    }

    public void ganhou() {

        int contador = 0; // contar quantas jogadas já foram feitas
        
        for (int jogadas = 0; jogadas < 9; jogadas++) {
            
            if (clicouBotao[jogadas] == true) {
                contador++;
            }
            
        }

        if ((bn1.getText().equals("X") && bn2.getText().equals("X") && bn3.getText().equals("X"))
                || (bn1.getText().equals("X") && bn4.getText().equals("X") && bn7.getText().equals("X"))
                || (bn1.getText().equals("X") && bn5.getText().equals("X") && bn9.getText().equals("X"))
                || (bn3.getText().equals("X") && bn5.getText().equals("X") && bn7.getText().equals("X"))
                || (bn4.getText().equals("X") && bn5.getText().equals("X") && bn6.getText().equals("X"))
                || (bn3.getText().equals("X") && bn6.getText().equals("X") && bn9.getText().equals("X"))
                || (bn7.getText().equals("X") && bn8.getText().equals("X") && bn9.getText().equals("X"))) {

            exibirMensagem("O " + nomeJogadores[0] + " ganhou essa");
        
        } else if ((bn1.getText().equals("O") && bn2.getText().equals("O") && bn3.getText().equals("O"))
                || (bn1.getText().equals("O") && bn4.getText().equals("O") && bn7.getText().equals("O"))
                || (bn1.getText().equals("O") && bn5.getText().equals("O") && bn9.getText().equals("O"))
                || (bn3.getText().equals("O") && bn5.getText().equals("O") && bn7.getText().equals("O"))
                || (bn4.getText().equals("O") && bn5.getText().equals("O") && bn6.getText().equals("O"))
                || (bn3.getText().equals("O") && bn6.getText().equals("O") && bn9.getText().equals("O"))
                || (bn7.getText().equals("O") && bn8.getText().equals("O") && bn9.getText().equals("O"))) {

            exibirMensagem("O " + nomeJogadores[1] + " ganhou essa");

        } else if (contador == 9) {
            exibirMensagem("Cês são ruim em! \n\n Deu Velha");
        }
    }
    
     public void exibirMensagem(String mensagem) {
        int option = JOptionPane.showOptionDialog(null, mensagem, "Resultado do Jogo", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        
        if (option == JOptionPane.OK_OPTION) {
            limpar();
        }
    }

    public void limpar() {
        
        for (javax.swing.JButton button : new javax.swing.JButton[]{bn1, bn2, bn3, bn4, bn5, bn6, bn7, bn8, bn9}) {
            button.setText("");
        }
        
        
        Arrays.fill(clicouBotao, false);
        vezJogador = false;
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn1;
    private javax.swing.JButton bn2;
    private javax.swing.JButton bn3;
    private javax.swing.JButton bn4;
    private javax.swing.JButton bn5;
    private javax.swing.JButton bn6;
    private javax.swing.JButton bn7;
    private javax.swing.JButton bn8;
    private javax.swing.JButton bn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomeJogador;
    // End of variables declaration//GEN-END:variables
}
