/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atividadesextras;

import java.awt.Color;
import java.util.Random;
import javax.swing.JFrame;
import static javax.swing.text.StyleConstants.Background;

/**
 *
 * @author Kauã Rodrigo
 */
public class MudarCor extends javax.swing.JFrame {

    /**
     * Creates new form MudarCor
     */
    public MudarCor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntCorFundo = new javax.swing.JButton();
        corAtual = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntCorFundo.setText("Mudar Cor de Fundo");
        bntCorFundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCorFundoActionPerformed(evt);
            }
        });
        getContentPane().add(bntCorFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 199, -1, -1));

        corAtual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        corAtual.setText("Cor");
        getContentPane().add(corAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 103, 71, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 191, 10));

        jTextField1.setBackground(new java.awt.Color(51, 153, 255));
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCorFundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCorFundoActionPerformed
        // TODO add your handling code here:
        
        Random corAle = new Random();
        
        int color1 = corAle.nextInt(257) + 100 ;
        int color2 = corAle.nextInt(257) + 100 ;
        int color3 = corAle.nextInt(256) + 90 ;
        
        Color random = new Color(color1, color2, color3);
        
        getContentPane().setBackground(random);
        
        bntCorFundo.setBackground(random);
        
        corAtual.setText(Integer.toString(random.getRGB()));
        
    }//GEN-LAST:event_bntCorFundoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MudarCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MudarCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MudarCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MudarCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MudarCor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCorFundo;
    private javax.swing.JLabel corAtual;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
