/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiposdetraingulos;

/**
 *
 * @author Kauã Rodrigo
 */
public class Triangulos extends javax.swing.JFrame {

    /**
     * Creates new form Triangulos
     */
    public Triangulos() {
        initComponents();
        
        // vai deixar o painel escondido quando inicializar o programa
        panResposta.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bntVerificar = new javax.swing.JButton();
        slideA = new javax.swing.JSlider();
        slideB = new javax.swing.JSlider();
        slideC = new javax.swing.JSlider();
        panResposta = new javax.swing.JPanel();
        textStatus = new javax.swing.JLabel();
        textTipo = new javax.swing.JLabel();
        valorC = new javax.swing.JLabel();
        valorA = new javax.swing.JLabel();
        valorB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Segmento A :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Segmento B :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 136, 91, 16));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Segmento C :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 91, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tipos de Triângulos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 527, 10));

        bntVerificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVerificar.setText("Verificar");
        bntVerificar.setMaximumSize(new java.awt.Dimension(20, 20));
        bntVerificar.setMinimumSize(new java.awt.Dimension(0, 0));
        bntVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(bntVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 228, -1, -1));

        slideA.setMaximum(20);
        slideA.setValue(0);
        slideA.setMaximumSize(new java.awt.Dimension(20, 20));
        slideA.setMinimumSize(new java.awt.Dimension(0, 0));
        slideA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideAStateChanged(evt);
            }
        });
        getContentPane().add(slideA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 151, 20));

        slideB.setMaximum(20);
        slideB.setValue(0);
        slideB.setMaximumSize(new java.awt.Dimension(20, 20));
        slideB.setMinimumSize(new java.awt.Dimension(0, 0));
        slideB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideBStateChanged(evt);
            }
        });
        getContentPane().add(slideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 151, 30));

        slideC.setMaximum(20);
        slideC.setValue(0);
        slideC.setMaximumSize(new java.awt.Dimension(20, 20));
        slideC.setMinimumSize(new java.awt.Dimension(0, 0));
        slideC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideCStateChanged(evt);
            }
        });
        getContentPane().add(slideC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 151, 30));

        textStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textStatus.setForeground(new java.awt.Color(102, 204, 255));
        textStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textStatus.setText("Forma ou não ?");

        textTipo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textTipo.setForeground(new java.awt.Color(255, 153, 51));
        textTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTipo.setText("Tipo de triângulo");

        javax.swing.GroupLayout panRespostaLayout = new javax.swing.GroupLayout(panResposta);
        panResposta.setLayout(panRespostaLayout);
        panRespostaLayout.setHorizontalGroup(
            panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panRespostaLayout.setVerticalGroup(
            panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespostaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textStatus)
                .addGap(18, 18, 18)
                .addComponent(textTipo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(panResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 273, 467, -1));

        valorC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorC.setForeground(new java.awt.Color(0, 0, 0));
        valorC.setText("C");
        getContentPane().add(valorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        valorA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorA.setForeground(new java.awt.Color(0, 0, 0));
        valorA.setText("A");
        getContentPane().add(valorA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        valorB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorB.setForeground(new java.awt.Color(0, 0, 0));
        valorB.setText("B");
        getContentPane().add(valorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kauã Rodrigo\\Downloads\\traingulo.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 53, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerificarActionPerformed
        // TODO add your handling code here:
        
        panResposta.setVisible(true);
        
        int a = slideA.getValue();
        int b = slideB.getValue();
        int c = slideC.getValue();
        
        if (a < b + c && b < a + c && c < a + b) {
            textStatus.setText("Formam um Triângulo");
            
            if (a == b && b == c) {
                textTipo.setText("Equilátero");
            } else if (a != b && b != c && c != a) {
                textTipo.setText("Escaleno");
            } else {
                textTipo.setText("Isósceles");
            }
        } else {
            textStatus.setText("Não Formam um Triângulo");
            textTipo.setText("---");
        }
        
        
    }//GEN-LAST:event_bntVerificarActionPerformed

    private void slideAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideAStateChanged
        // TODO add your handling code here:
        
        // pegar o valor do slideA 
        valorA.setText(Integer.toString(slideA.getValue()));
                
    }//GEN-LAST:event_slideAStateChanged

    private void slideBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideBStateChanged
        // TODO add your handling code here:
        
        // pegar o valor do slideB
        valorB.setText(Integer.toString(slideB.getValue()));
        
    }//GEN-LAST:event_slideBStateChanged

    private void slideCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideCStateChanged
        // TODO add your handling code here:
        
        // pegar o valor do slideC
        valorC.setText(Integer.toString(slideC.getValue()));
        
    }//GEN-LAST:event_slideCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panResposta;
    private javax.swing.JSlider slideA;
    private javax.swing.JSlider slideB;
    private javax.swing.JSlider slideC;
    private javax.swing.JLabel textStatus;
    private javax.swing.JLabel textTipo;
    private javax.swing.JLabel valorA;
    private javax.swing.JLabel valorB;
    private javax.swing.JLabel valorC;
    // End of variables declaration//GEN-END:variables
}
